server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    repositories:
      bootstrap-mode: default
  datasource:
    url: jdbc:h2:mem:inditexdb
    username: jairo
    password: passwd
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true